# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2025, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# python-doc bot, 2025
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.11\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-10-15 16:36+0000\n"
"PO-Revision-Date: 2025-09-22 16:49+0000\n"
"Last-Translator: python-doc bot, 2025\n"
"Language-Team: Swedish (https://app.transifex.com/python-doc/teams/5390/"
"sv/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: sv\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../../library/asyncio-exceptions.rst:8
msgid "Exceptions"
msgstr "Undantag"

#: ../../library/asyncio-exceptions.rst:10
msgid "**Source code:** :source:`Lib/asyncio/exceptions.py`"
msgstr "**Källkod:** :source:`Lib/asyncio/exceptions.py`"

#: ../../library/asyncio-exceptions.rst:16
msgid ""
"A deprecated alias of :exc:`TimeoutError`, raised when the operation has "
"exceeded the given deadline."
msgstr ""
"Ett föråldrat alias för :exc:`TimeoutError`, som uppstår när operationen har "
"överskridit den angivna tidsgränsen."

#: ../../library/asyncio-exceptions.rst:21
msgid "This class was made an alias of :exc:`TimeoutError`."
msgstr "Denna klass gjordes till ett alias för :exc:`TimeoutError`."

#: ../../library/asyncio-exceptions.rst:26
msgid "The operation has been cancelled."
msgstr "Operationen har avbrutits."

#: ../../library/asyncio-exceptions.rst:28
msgid ""
"This exception can be caught to perform custom operations when asyncio Tasks "
"are cancelled.  In almost all situations the exception must be re-raised."
msgstr ""
"Detta undantag kan fångas för att utföra anpassade operationer när asyncio "
"Tasks avbryts.  I nästan alla situationer måste undantaget tas upp på nytt."

#: ../../library/asyncio-exceptions.rst:34
msgid ""
":exc:`CancelledError` is now a subclass of :class:`BaseException` rather "
"than :class:`Exception`."
msgstr ""
":exc:`CancelledError` är nu en subklass av :class:`BaseException` istället "
"för :class:`Exception`."

#: ../../library/asyncio-exceptions.rst:39
msgid "Invalid internal state of :class:`Task` or :class:`Future`."
msgstr "Ogiltigt internt tillstånd för :class:`Task` eller :class:`Future`."

#: ../../library/asyncio-exceptions.rst:41
msgid ""
"Can be raised in situations like setting a result value for a *Future* "
"object that already has a result value set."
msgstr ""
"Kan uppstå i situationer som att ange ett resultatvärde för ett *Future*-"
"objekt som redan har ett resultatvärde angivet."

#: ../../library/asyncio-exceptions.rst:47
msgid ""
"The \"sendfile\" syscall is not available for the given socket or file type."
msgstr ""
"Syscallen \"sendfile\" är inte tillgänglig för den angivna socket- eller "
"filtypen."

#: ../../library/asyncio-exceptions.rst:50
msgid "A subclass of :exc:`RuntimeError`."
msgstr "En underklass till :exc:`RuntimeError`."

#: ../../library/asyncio-exceptions.rst:55
msgid "The requested read operation did not complete fully."
msgstr "Den begärda läsoperationen slutfördes inte helt och hållet."

#: ../../library/asyncio-exceptions.rst:57
msgid "Raised by the :ref:`asyncio stream APIs<asyncio-streams>`."
msgstr "Utlöstes av :ref:`asyncio stream APIs<asyncio-streams>`."

#: ../../library/asyncio-exceptions.rst:59
msgid "This exception is a subclass of :exc:`EOFError`."
msgstr "Detta undantag är en subklass av :exc:`EOFError`."

#: ../../library/asyncio-exceptions.rst:63
msgid "The total number (:class:`int`) of expected bytes."
msgstr "Det totala antalet (:class:`int`) förväntade bytes."

#: ../../library/asyncio-exceptions.rst:67
msgid "A string of :class:`bytes` read before the end of stream was reached."
msgstr ""
"En sträng av :class:`bytes` som lästes innan slutet av strömmen nåddes."

#: ../../library/asyncio-exceptions.rst:72
msgid "Reached the buffer size limit while looking for a separator."
msgstr "Nådde gränsen för buffertstorlek när jag letade efter en separator."

#: ../../library/asyncio-exceptions.rst:74
msgid "Raised by the :ref:`asyncio stream APIs <asyncio-streams>`."
msgstr "Utlöstes av :ref:`asyncio stream APIs <asyncio-streams>`."

#: ../../library/asyncio-exceptions.rst:78
msgid "The total number of to be consumed bytes."
msgstr "Det totala antalet bytes som ska konsumeras."
